Tree equivalence
katiasuya/tree pull request #1
Opened 2021-01-06 12:34 UTC by katiasuya

2021-01-06 12:38 UTC, katiasuya commented
I think I should handle the error if the user uses not int in New() function, should I?

2021-01-06 15:20 UTC, papahmsolo requested changes
I have to say, tests are good

2021-01-06 15:20 UTC, papahmsolo commented on tree_test1.go
> +	}
Try to `range` over the channel, it's much cleaner code

2021-01-06 15:20 UTC, papahmsolo commented on tree1.go
> +import "golang.org/x/tour/tree"
A little copying is better than a little dependency: https://www.youtube.com/watch?v=PAAkCSZUG1c&t=9m28s

2021-01-06 15:20 UTC, papahmsolo commented on tree1.go
> +import "golang.org/x/tour/tree"
We don't really need that dependency, do we? We just need the `Tree` type.

2021-01-06 15:37 UTC, katiasuya commented on tree1.go
> +import "golang.org/x/tour/tree"
You're right, I've complicated it one more time.

2021-01-08 08:12 UTC, papahmsolo requested changes
Looks very good!

2021-01-08 08:12 UTC, papahmsolo commented on tree.go
> +	var t *Tree
We can make it a named return variable, thus we won't need the declaration.

2021-01-08 08:12 UTC, papahmsolo commented on tree.go
> +		return &Tree{Left: nil, Value: v, Right: nil}
No need to set `Left` and `Right` to `nil`, they'll get it by default

2021-01-08 08:12 UTC, papahmsolo commented on tree_test.go
> +	}
We can to this comparison easier with `reflect.DeepEqual()`

2021-01-08 08:12 UTC, papahmsolo commented on tree_test.go
> +func BenchmarkSame(b *testing.B) {
Let's create a benchmark for two large trees, we wat to assess the performance here

2021-01-08 10:58 UTC, papahmsolo requested changes
👍

2021-01-08 10:58 UTC, papahmsolo commented on tree_test.go
> +			var nums []int
If we use `nums := []int{}` right away we won't need to check it for nil later

2021-01-08 10:58 UTC, papahmsolo commented on tree_test.go
> +			in2:  []int{5, -9, 14, 0, 17, -1, 2, -55, 16, 4},
By large I mean something really large, say 1000 nodes at least. Try `rand.Perm()`, it might help you with tree generation

2021-01-08 11:02 UTC, katiasuya commented on tree_test.go
> +			var nums []int
But what if we pass a nil value?

2021-01-11 09:29 UTC, papahmsolo approved these changes
Nice work!

2021-01-11 09:29 UTC, merged